apiVersion: api
kind: RiplicaSet
metadata:
  name: my-first-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      project: My-firstProj
      ver: 0.1
  template:
    metadata:
      name: my-first-pod
      lables:
        project: myfirstProj
        ver: 0.1
    spec:
      image: httpd
      ports:
      - containerPort: 99

